#!/bin/bash



service=$1
action=$2



usage(){
  echo "Usage: $0 <SERVICE> <ACTION>"
  echo "SERVICE : < {namenode|NN} | {datanode|DN} | {journalnode|JN} | {datanode|DN} \\"
  echo "            {journalnode|JN} | {dfszkfailovercontroller|FC} \\"
  echo "            {resourcemanager|RM} | {nodemanager|NM} {HistoryServer|HS}\\"
  echo "            {hmaster|HM} | {hregionserver|RS} | {quorumpeermain|ZK} \\"
  echo "            {hiveserver2|HS2} | {hivemetastore|HMS} \\"
  echo "            {myimpala_state_store|IMS} | {myimpala_catalog|ICL} | {myimpala_server|ISD}"
  echo "ACTION  : < start|stop >"
  exit 0
}

service_run() {


hos=$1
srv=$2
act=$3


  case "$srv" in
    resourcemanager|RM)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/yarn-daemon.sh --config /opt/hadoop/etc/hadoop $act resourcemanager"
      ;;
    nodemanager|NM)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/yarn-daemon.sh --config /opt/hadoop/etc/hadoop $act nodemanager"
      ;;
    historyserver|HS)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/mr-jobhistory-daemon.sh --config /opt/hadoop/etc/hadoop $act historyserver"
      ;;
    datanode|DN)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/hadoop-daemon.sh --config /opt/hadoop/etc/hadoop $act datanode"
      ;;
    namenode|NN
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/hadoop-daemon.sh --config /opt/hadoop/etc/hadoop $act namenode"
      ;;
    DFSZKFailoverController|FC)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/hadoop-daemon.sh --config /opt/hadoop/etc/hadoop $act zkfc"
      ;;
    journalnode|JN)
      ssh $hos ". /etc/profile; /opt/hadoop/sbin/hadoop-daemon.sh --config /opt/hadoop/etc/hadoop $act journalnode"
      ;;
    hivemetastore|HMS)
      ssh $hos ". /etc/profile; /opt/hive/sbin/hive-daemon.sh $act metastore"
      ;;
    hiveserver2|HS2)
      ssh $hos ". /etc/profile; /opt/hive/sbin/hive-daemon.sh $act hiveserver2"
      ;;
    myimpala_state_store|IMS)
      ssh $hos ". /etc/profile; /opt/impala/init.d/myimpala_state_store $act"
      ;;
    myimpala_catalog|ICL)
      ssh $hos ". /etc/profile; /opt/impala/init.d/myimpala_catalog $act"
      ;;
    myimpala_server|ISD)
      ssh $hos ". /etc/profile; /opt/impala/init.d/myimpala_server $act"
      ;;
    quorumpeermain|ZK)
      ssh $hos ". /etc/profile; /opt/zookeeper/bin/zkServer.sh $act"
      ;;
    hmaster|HM)
      ssh $hos ". /etc/profile; /opt/hbase/bin/hbase-daemon.sh --config /opt/hbase/conf $act master"
      ;;
    hregionserver|RS)
      ssh $hos ". /etc/profile; /opt/hbase/bin/hbase-daemon.sh --config /opt/hbase/conf $act regionserver"
      ;;
    *)
      usage
  esac
}


check_for_root() {
  if [ $(id -ur) -eq 0 ] || [ $(id -ur) -eq $(id $SVC_USER -ur) ]; then
    echo "welcome : $(id -un)!"
  else
    echo 'Error: root user required'
    echo
    exit 1
  fi

}


## rm stop
##yarn-daemon.sh --config $YARN_CONF_DIR  stop resourcemanager

check_for_root



svr_host=$(cat ./service_hosts | grep -v "#" | grep -w $1 | awk {'print $2'})

if [ "$2" == "" ] || [ "$svr_host" == "" ]; then
  usage
fi


for host in $svr_host;do
        echo "=== $host === "
	service_run $host $service $action

done




